FORMAT: 1A

# hfbiz-service-cuzk

Is service for providing CUZK functions easily available by REST interface.


# Group Account

Manage the account.


## renewalPassword [/renewalPassword]

Renew the password when comes out of date.

### ­ [GET]

+ Response 200



# Group Reports

Operations with reports.


## generujLV [/generujLV?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"lvId": 0`
        
        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/json)


## generujLVPresObjekty [/generujLVPresObjekty?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"seznamuObjektuTyp": ""`

        `"seznamObjektu": ""`

        `"castecnyVypis": "n"`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/json)


## generujLVZjednodusene [/generujLVZjednodusene?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"katastrUzemiKod": 0`

        `"lvCislo": 0`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/json)


## generujMapu [/generujMapu?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"parcelaId": null`

        `"souradniceX": null`

        `"souradniceY": null`

        `"formatPapiru": "A4"`

        `"orientaceNaSirku": "n"`

        `"meritkoMapy": 1000`

        `"vecnaBremena": "n"`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/json)


## generujPrehledVlastnictvi [/generujPrehledVlastnictvi?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"osId": 0`
        
        `"krajKod": null`
        
        `"obecKod": null`
        
        `"typPravnihoVztahu": null`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)
        
+ Response 200 (application/json)


## seznamSestav [/seznamSestav?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"idSestavy": null`


### ­ [GET]

Parameters with value `null` are not required.

If `idSestavy` is set to `null`, return result will be all the list.

+ Request (application/json)

+ Response 200 (application/json)


## smazSestavu [/smazSestavu?params={params}]
    
+ Parameters 

    + params (object) - valid JSON object of params

        `"idSestavy": 0`


### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)
        
+ Response 200 (application/json)


## vratGenerovanyLV [/vratGenerovanyLV?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"lvId": 0`
        
        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/pdf)


## vratGenerovanyLVPresObjekty [/vratGenerovanyLVPresObjekty?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"seznamuObjektuTyp": ""`

        `"seznamObjektu": ""`

        `"castecnyVypis": "n"`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/pdf)


## vratGenerovanyLVZjednodusene [/vratGenerovanyLVZjednodusene?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"katastrUzemiKod": 0`

        `"lvCislo": 0`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/pdf)


## vratGenerovanouMapu [/vratGenerovanouMapu?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"parcelaId": null`

        `"souradniceX": null`

        `"souradniceY": null`

        `"formatPapiru": "A4"`

        `"orientaceNaSirku": "n"`

        `"meritkoMapy": 1000`

        `"vecnaBremena": "n"`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)

+ Response 200 (application/pdf)


## vratGenerovanyPrehledVlastnictvi [/vratGenerovanyPrehledVlastnictvi?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"osId": 0`
        
        `"krajKod": null`
        
        `"obecKod": null`
        
        `"typPravnihoVztahu": null`

        `"format": "pdf"`
        
        `"cisloJednaci": null`
        
        `"ucelKod": null`

### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)
        
+ Response 200 (application/pdf)


## vratSestavu [/vratSestavu?params={params}]

+ Parameters 

    + params (object) - valid JSON object of params

        `"idSestavy": 0`
        

### ­ [GET]

+ Request (application/json)
        
+ Response 200 (application/pdf)



# Group Searching


## najdiOS [/najdiOS?params={params}]

+ Parameters

    + params (object) - valid JSON object of params

        `"nazev": null`
        
        `"ico": null`
        
        `"rc": null`
        
### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)
        
+ Response 200 (application/json)


## najdiParcelu [/najdiParcelu?params={params}]

+ Parameters

    + params (object) - valid JSON object of params

        `"katastrUzemiKod": 0`
        
        `"kmenoveCislo": 0`
        
        `"poddeleni": null`
        
### ­ [GET]

Parameters with value `null` are not required.

+ Request (application/json)
        
+ Response 200 (application/json)


## najdiStavbu [/najdiStavbu?params={params}]

+ Parameters

    + params (object) - valid JSON object of params

        `"castObceKod": 0`
        
        `"typStavbyKod": 0`
        
        `"cisloDomovni": 0`
        
### ­ [GET]

+ Request (application/json)
        
+ Response 200 (application/json)


