FORMAT: 1A

# hfbiz-service-cuzk

Is service for providing CUZK functions easily available by REST interface.


# Reports


## generujLV [/generujLV]

Parameters with value `null` are not required.

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                lvId: 0,
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## generujLVPresObjekty [/generujLVPresObjekty]
    
Parameters with value `null` are not required.

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                seznamuObjektuTyp: '',
                seznamObjektu: '',
                castecnyVypis: 'n',
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## generujLVZjednodusene [/generujLVZjednodusene]
    
Parameters with value `null` are not required.

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                katastrUzemiKod: 0,
                lvCislo: 0,
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## generujMapu [/generujMapu]
    
Parameters with value `null` are not required.

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                parcelaId: null,
                souradniceX: null,
                souradniceY: null,
                formatPapiru: 'A4',
                orientaceNaSirku: 'n',
                meritkoMapy: 1000,
                vecnaBremena: 'n',
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## generujPrehledVlastnictvi [/generujPrehledVlastnictvi]
    
Parameters with value `null` are not required.

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                osId: 0,
                krajKod: null,
                obecKod: null,
                typPravnihoVztahu: null,
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## seznamSestav [/seznamSestav]
    
Parameters with value `null` are not required.

If `idSestavy` is set to `null`, return result will be all the list.

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                idSestavy: null
            }
        
+ Response 200 (application/json)


## smazSestavu [/smazSestavu]
    
### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                idSestavy: 0
            }
        
+ Response 200 (application/json)


