FORMAT: 1A

# hfbiz-service-cuzk

Is service for providing CUZK functions easily available by REST interface.


# Reports

Parameters with value `null` are not required.


## generujLV [/generujLV]

### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                lvId: 0,
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## generujLVPresObjekty [/generujLVPresObjekty]
    
### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                seznamuObjektuTyp: '',
                seznamObjektu: '',
                castecnyVypis: 'n',
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


## generujLVZjednodusene [/generujLVZjednodusene]
    
### ­ [GET]

+ Request (application/json)

    + Body
    
            {
                katastrUzemiKod: 0,
                lvCislo: 0,
                format: 'pdf',
                cisloJednaci: null,
                ucelKod: null
            }
        
+ Response 200 (application/json)


